// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9p84YFSaRrWYI5c2Dm4CwmgtJuWTys9g',
    appId: '1:701389143848:web:3cc71c72b92baac7d55a1d',
    messagingSenderId: '701389143848',
    projectId: 'aiden-shiv',
    authDomain: 'aiden-shiv.firebaseapp.com',
    storageBucket: 'aiden-shiv.appspot.com',
    measurementId: 'G-RNTHBZZKJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_f3CS7JM3jVYvuj4M9GdVlOwUsu5oBsQ',
    appId: '1:701389143848:android:659b3aa854d0f453d55a1d',
    messagingSenderId: '701389143848',
    projectId: 'aiden-shiv',
    storageBucket: 'aiden-shiv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz3obFvgcKQgqzmJx9lqfmfkPvT6okx5k',
    appId: '1:701389143848:ios:d7af9c0be6eab6d3d55a1d',
    messagingSenderId: '701389143848',
    projectId: 'aiden-shiv',
    storageBucket: 'aiden-shiv.appspot.com',
    iosClientId: '701389143848-4j6bat8bktk9oh1gijp7e8mn1rp82rdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz3obFvgcKQgqzmJx9lqfmfkPvT6okx5k',
    appId: '1:701389143848:ios:1b69e6e2b584395fd55a1d',
    messagingSenderId: '701389143848',
    projectId: 'aiden-shiv',
    storageBucket: 'aiden-shiv.appspot.com',
    iosClientId: '701389143848-g43j02g0v14d8h7kh3snsq5hrv60dhs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiden.RunnerTests',
  );
}
