name: tensorical
description: "A new Flutter project."
publish_to: 'none' # This line prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Ensure your SDK version is correct for your Flutter version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^1.10.0 # Use the latest version compatible with your Flutter version
  firebase_auth: ^3.3.5 # Use the latest version compatible with your Flutter version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # Add your asset directories here, if you have any. Since you mentioned not having foreground things, you might not need to add anything here.
    # - assets/images/
  
  # If you later add custom fonts or other assets, you can uncomment and modify the following sections accordingly.
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFontFamily-Regular.ttf
  #       - asset: fonts/YourFontFamily-Italic.ttf
  #         style: italic
  #       - asset: fonts/YourFontFamily-Bold.ttf
  #         weight: 700

